[Nickname] # 现在没用
nickname = ""

[Napcat_Server] # Napcat连接的ws服务设置
host = "localhost" # Napcat设定的主机地址
port = 8095        # Napcat设定的端口
heartbeat = 30     # 与Napcat设置的心跳相同（按秒计）

[MaiBot_Server] # 连接麦麦的ws服务设置
platform_name = "qq" # 标识adapter的名称（必填）
host = "localhost"   # 麦麦在.env文件中设置的主机地址，即HOST字段
port = 8000          # 麦麦在.env文件中设置的端口，即PORT字段

[Chat] # 黑白名单功能
list_type = "whitelist" # 使用的白名单类型，可选为：whitelist, blacklist
# 当list_type为whitelist时，使用白名单模式，以下两个列表的含义是：仅允许名单中的人聊天
# 当list_type为blacklist时，使用黑名单模式，以下两个列表的含义是：禁止名单中的人聊天
group_list = [] # 群组名单
user_list = [] # 私聊名单
ban_user_id = [] # 禁止名单（禁止名单中的人无法使用任何功能）

[Voice] # 发送语音设置
use_tts = false # 是否使用tts语音（请确保你配置了tts并有对应的adapter）

[Debug]
level = "INFO" # 日志等级（DEBUG, INFO, WARNING, ERROR）
